### ISSUE TITLE
Two Github Actions fails on master branch

### ISSUE THREAD

**Issue by adamqqqplay** [dragonflyoss/image-service#1301]
## Additional Information
_The following information is very important in order to help us to help you. Omission of the following details may delay your support request or receive no attention at all._

### 1. Action: Convert & Check Images
Convert & Check Images fails since May 23, 2023, bug probably introduced by #1257.
Nydusify check reported this error: https://github.com/dragonflyoss/image-service/actions/runs/5063307750/jobs/9089815587
```
time="2023-05-24T00:25:47Z" level=info msg="Verified Nydus image localhost:5000/alpine:nydus-nightly-v6"
<E> erofs: corrupted `..' dirent @ nid 128, lblk 0, index 1
<E> erofs: Found some filesystem corruption
```

It may be necessary to make changes in nydusify or nydus-image, and maintain compatibility with older versions.

### 2. Action: Release
Release fails since May 23, 2023, bug probably introduced by #1257.
Cargo build reported this error: https://github.com/dragonflyoss/image-service/actions/runs/5062514078/jobs/9088121838
```
error[E0308]: mismatched types
   --> rafs/src/builder/stargz.rs:[24](https://github.com/dragonflyoss/image-service/actions/runs/5062514078/jobs/9088121838#step:4:25)9:21
    |
249 |         self.mode & !libc::S_IFMT | mode as u32
    |                     ^^^^^^^^^^^^^ expected `u32`, found `u16`

error[E0277]: no implementation for `u32 & u16`
   --> rafs/src/builder/stargz.rs:249:19
    |
249 |         self.mode & !libc::S_IFMT | mode as u32
    |                   ^ no implementation for `u32 & u16`
    |
    = help: the trait `BitAnd<u16>` is not implemented for `u[32](https://github.com/dragonflyoss/image-service/actions/runs/5062514078/jobs/9088121838#step:4:33)`
    = help: the following other types implement trait `BitAnd<Rhs>`:
              <&'a u32 as BitAnd<u32>>
              <&u32 as BitAnd<&u32>>
              <u32 as BitAnd<&u32>>
              <u32 as BitAnd>
```
It may be necessary to do some processing for compilation on macos.
